### ISSUE TITLE
[Future Enhancement] Automated testing framework?

### ISSUE THREAD

**Issue by ASleepyCat** [m4saka/kshootmania-v2#37] opened 2023-07-05 10:10 UTC
Any plans to implement some sort of automated testing (unit tests, interface tests)?

**Comment by m4saka** [comment] 2023-07-05 14:45
@ASleepyCat 
Right now, I'm not planning to introduce test code because our focus is on finishing the project and getting it released.

That being said, do you have any thoughts on which parts of the program might benefit from testing?

I think it might be worth writing test code for chart loading/saving (libkson library), but for the game itself, I feel the benefit of writing tests is somewhat limited.

**Comment by ASleepyCat** [comment] 2023-07-05 23:48
Having tests for parts of the gameplay loop would make validations for those a lot easier.

When I was reimplementing parts of SDVX into USC, I had to rely on reasoning about my code and manually testing to see if my changes fit my expectations. I couldn't really debug and step through line-by-line since I couldn't precisely control the delta time between game loops. This meant I was never 100% confident about my changes.

You could also simulate lag spikes/stuttering and see how the game handles them.

Obviously there's also the usual stuff with tests like detecting regressions, code coverage, readability (maybe?), etc.

**Comment by m4saka** [comment] 2023-07-06 12:52
Indeed, in rhythm game development, it is difficult to debug step by step with a regular debugger, so we have to rely on our senses for testing.... I understand that very well, too.
But so far, in KSMv2, I haven't encountered a situation where step execution is necessary to fix a bug. If such a problem comes up, I will add a debugging feature!

Also, since I am currently a one-person developer in this project, regression testing doesn't provide much benefit, but it is certainly a good idea considering incorporating contributions from others in the future. I'll keep that in mind!

**Comment by m4saka** [comment] 2023-08-06 20:31
Closed as we won't implement this before the first release.
We may reopen it after the first release.

**Closed as completed by m4saka** 2023-08-06 20:31 UTC
Labels: enhancement
